### PR TITLE
Add support for es v7 and php 7.3

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by snapshotpl** [comment]
@jeskew all tests pass, PR is ready to :ship:

**Comment by snapshotpl** [comment]
@victorwelling can you review and merge this one?

**Comment by victorwelling** [comment]
> @victorwelling can you review and merge this one?

I'm not the maintainer of this package, so unfortunately I can't help you. I think you'll have to wait for @jeskew to take a look at it.

**Comment by jeskew** [comment]
Closing in favor of #20

**Pull request closed without merging**
